#include <stdio.h>

int main() {
    int branches = 3;
    int products = 4;
    int shipments[3][4] = {
        {10, 20, 5, 12},   
        {7,  8,  15, 10},  
        {12, 18, 9,  14}   
    
}
    
    float revenuePerUnit[4] = {100.5, 75.0, 50.25, 120.0};

    float totalRevenue[3] = {0};


    for (int i = 0; i < branches; i++) {
        for (int j = 0; j < products; j++) {
            totalRevenue[i] += shipments[i][j] * revenuePerUnit[j];
        }
    }

    
    printf("Total Revenue Generated by Each Branch:\n");
    for (int i = 0; i < branches; i++) {
        printf("Branch %d: ₹%.2f\n", i + 1, totalRevenue[i]);
    }

    return 0;
}
